#spring.application.name=shopping-service

#Application Configuration
server:
  port: 8093
  error:
    include-message: always #Se agrega por que ResponseStatusException no muestra la Reason del error al crear un producto
    
# To See H2 Console in Browser:
# http://localhost:8093/h2-console
# Enabling H2 Console
spring:
  application:
    name: shopping-service
  h2:
    console:
      enabled: true
  # ===============================
  # DB
  # ===============================
  datasource:
    url: jdbc:h2:file:~/digitalLabServiceShopping;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
#    platform: h2
    username: sa
    password:
  sql:
    init:
      platform: h2

  # ===============================
  # JPA / HIBERNATE
  # ===============================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/
  instance:
    preferIpAddress: true